import typer
import subprocess
import os
import sys
import shutil
from pathlib import Path
from typing import Optional
from jarvis.config import get_secrets, save_secrets, JARVIS_ROOT, CONFIG_DIR, BIN_DIR # Removed unused LEGACY_DIR

app = typer.Typer(
    help="Self-management and JARVIS setup commands",
    no_args_is_help=True,
)


def sync_ssh_keys():
    """
    Sync SSH authorized_keys from /etc/jarvis (or CONFIG_DIR) to ~/.ssh/authorized_keys.
    """
    auth_keys_src = CONFIG_DIR / "authorized_keys"
    auth_keys_dest = Path.home() / ".ssh/authorized_keys"

    if not auth_keys_src.exists():
        print(f"⚠️  Source authorized_keys not found at {auth_keys_src}")
        return

    # Check source has actual keys before proceeding
    source_keys = []
    with open(auth_keys_src, "r") as f:
        for line in f:
            key = line.strip()
            if key and not key.startswith("#"):
                source_keys.append(key)

    if not source_keys:
        print(f"⚠️  authorized_keys at {auth_keys_src} is empty, skipping.")
        return

    print(f"🔑 Syncing SSH authorized_keys from {auth_keys_src}...")

    # Ensure destination directory exists
    auth_keys_dest.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    if not auth_keys_dest.exists():
        auth_keys_dest.touch(mode=0o600)

    # Read current keys to avoid duplicates
    try:
        with open(auth_keys_dest, "r") as f:
            current_keys = [k.strip() for k in f.readlines() if k.strip()]
    except Exception:
        current_keys = []

    new_keys_count = 0
    with open(auth_keys_dest, "a") as f_dest:
        for key in source_keys:
            if key not in current_keys:
                f_dest.write(key + "\n")
                new_keys_count += 1

    if new_keys_count > 0:
        print(f"✅ Added {new_keys_count} new SSH keys.")
    else:
        print("⏺️  All SSH keys are already present.")


def setup_vim():
    """
    Setup .vimrc by copying it from the jarvis config (internal step).
    """
    vimrc_src = CONFIG_DIR / ".vimrc"
    vimrc_dest = Path.home() / ".vimrc"
    if vimrc_src.exists():
        print(f"📝 Installing .vimrc from {vimrc_src}...")
        if vimrc_dest.exists() or vimrc_dest.is_symlink():
            print(f"⚠️  Overwriting existing {vimrc_dest}")
            if vimrc_dest.is_dir() and not vimrc_dest.is_symlink():
                shutil.rmtree(vimrc_dest)
            else:
                vimrc_dest.unlink()
        shutil.copy(vimrc_src, vimrc_dest)
        print(f"✅ Copied {vimrc_src} to {vimrc_dest}")
    else:
        print(f"❌ Error: {vimrc_src} not found.")


def setup_shell_integration():
    """
    Setup shell integration in ~/.bashrc and ~/.zshrc.
    Writes the actual commands to ~/.jarvis/shell_integration.sh and sources it.
    """
    import re
    
    # 1. Ensure ~/.jarvis exists
    JARVIS_ROOT.mkdir(parents=True, exist_ok=True)
    integration_sh_path = JARVIS_ROOT / "shell_integration.sh"

    # 2. Write logic to ~/.jarvis/shell_integration.sh
    integration_sh_src = CONFIG_DIR / "shell_integration.sh"
    if integration_sh_src.exists():
        sh_content = integration_sh_src.read_text()
    else:
        # Fallback in case the bundled file is missing or in development mode
        sh_content = (
            "# JARVIS Shell Integration\n"
            "# This file is generated by jarvis self deploy. Do not edit directly.\n\n"
            "# 1. sudo emulation for doas-only systems\n"
            "if ! command -v sudo >/dev/null 2>&1 && command -v doas >/dev/null 2>&1; then\n"
            "    sudo() {\n"
            "        local args=()\n"
            "        local preserve_env=0\n"
            "        while [[ $# -gt 0 ]]; do\n"
            "            case \"$1\" in\n"
            "                -E|--preserve-env) preserve_env=1; shift ;;\n"
            "                -u|--user) args+=(\"-u\" \"$2\"); shift 2 ;;\n"
            "                -s|--shell) args+=(\"-s\"); shift ;;\n"
            "                --) shift; break ;;\n"
            "                -*) shift ;;\n"
            "                *) break ;;\n"
            "            esac\n"
            "        done\n"
            "\n"
            "        if [ $preserve_env -eq 1 ]; then\n"
            "            doas \"${args[@]}\" env \"$@\"\n"
            "        else\n"
            "            doas \"${args[@]}\" \"$@\"\n"
            "        fi\n"
            "    }\n"
            "fi\n"
            "\n"
            "# 2. pct alias for Proxmox VE when using doas\n"
            "if command -v doas >/dev/null 2>&1 && [ -x /usr/sbin/pct ]; then\n"
            "    alias pct=\"doas -u root /usr/sbin/pct\"\n"
            "fi\n"
        )
    
    print(f"📝 Writing shell integration script to {integration_sh_path}...")
    integration_sh_path.write_text(sh_content)
    integration_sh_path.chmod(0o755)

    # 3. Setup loader block in shell rc files
    loader_code = (
        "\n# >>> JARVIS SHELL INTEGRATION >>>\n"
        "[ -f \"$HOME/.jarvis/shell_integration.sh\" ] && source \"$HOME/.jarvis/shell_integration.sh\"\n"
        "# <<< JARVIS SHELL INTEGRATION <<<\n"
    )

    home = Path.home()
    shell_files = [home / ".bashrc", home / ".zshrc"]
    
    for shell_file in shell_files:
        if not shell_file.exists():
            continue
            
        print(f"📝 Configuring shell loader in {shell_file}...")
        content = shell_file.read_text()
        
        # Check if JARVIS SHELL INTEGRATION block already exists
        start_marker = "# >>> JARVIS SHELL INTEGRATION >>>"
        end_marker = "# <<< JARVIS SHELL INTEGRATION <<<"
        
        if start_marker in content and end_marker in content:
            # Replace the existing block
            pattern = re.compile(rf"{re.escape(start_marker)}.*?{re.escape(end_marker)}", re.DOTALL)
            new_content = pattern.sub(loader_code.strip(), content)
        else:
            # Append to the end
            new_content = content.rstrip() + "\n" + loader_code
            
        shell_file.write_text(new_content)
        print(f"✅ Shell loader updated for {shell_file.name}")


@app.command()
def deploy():
    """
    Run the full JARVIS deployment/setup process.
    """
    print("🚀 Starting JARVIS deployment...")

    # 1. Setup VIM
    setup_vim()

    # 2. SSH Sync
    sync_ssh_keys()

    # 3. Setup Shell Integration
    setup_shell_integration()

    print("\n✨ Deployment complete!")
@app.command()
def update():
    """
    Check for and install the latest version of JARVIS from GitHub.
    """
    from rich.console import Console
    console = Console()
    
    # Detect the current executable path
    if getattr(sys, 'frozen', False):
        current_exe = Path(sys.executable).resolve()
    else:
        # Fallback for development mode
        console.print("[yellow]⚠️  Running in development mode. Update will replace the binary in ~/.local/bin/jarvis if it exists.[/yellow]")
        current_exe = Path.home() / ".local/bin/jarvis"
        if not current_exe.exists():
            console.print("[red]❌ Error: Cannot find binary to update in development mode.[/red]")
            return
            
    console.print(f"🚀 [bold blue]Updating JARVIS at:[/bold blue] [bold yellow]{current_exe}[/bold yellow]")
    
    tmp_file = "/tmp/jarvis.tar.gz"
    repo_url = "https://github.com/pigdome/jarvis/releases/latest/download/jarvis.tar.gz"
    
    # Clear LD_LIBRARY_PATH to avoid library conflicts when running system binaries (like curl)
    # from within a frozen PyInstaller bundle.
    env = os.environ.copy()
    for var in ['LD_LIBRARY_PATH', 'PYTHONHOME', 'PYTHONPATH']:
        env.pop(var, None)
            
    try:
        console.print(f"📥 Downloading latest version from [cyan]{repo_url}[/cyan]...")
        subprocess.run(["curl", "-L", repo_url, "-o", tmp_file], check=True, env=env)
        
        console.print("📦 Extracting binary...")
        # Extract jarvis from the tarball into /tmp
        subprocess.run(["tar", "-xzf", tmp_file, "-C", "/tmp", "jarvis"], check=True, env=env)
        
        new_exe = Path("/tmp/jarvis")
        if not new_exe.exists():
            console.print("[red]❌ Error: Extracted binary not found in tarball.[/red]")
            return

        console.print("🔄 Replacing current binary...")
        # On Linux, you cannot overwrite a running binary ([Errno 26] Text file busy).
        # But you CAN unlink (delete) or rename it. Unlinking allows us to 
        # put the new binary in its place.
        if current_exe.exists():
            current_exe.unlink()

        # Use shutil.copy2 to preserve permissions
        shutil.copy2(new_exe, current_exe)
        os.chmod(current_exe, 0o755)
        
        console.print("\n✨ [bold green]JARVIS has been successfully updated to the latest version![/bold green]")
        
    except subprocess.CalledProcessError:
        console.print("[red]❌ Error: Failed to download or extract the latest version.[/red]")
    except PermissionError:
        console.print("[red]❌ Error: Permission denied. Try running with sudo if necessary.[/red]")
    except Exception as e:
        console.print(f"[red]❌ Update failed: {e}[/red]")
    finally:
        # Cleanup
        if os.path.exists(tmp_file): os.remove(tmp_file)
        if os.path.exists("/tmp/jarvis"): os.remove("/tmp/jarvis")
