# JARVIS Shell Integration
# This file is generated by jarvis self deploy. Do not edit directly.

# 1. sudo emulation for doas-only systems
if ! command -v sudo >/dev/null 2>&1 && command -v doas >/dev/null 2>&1; then
    sudo() {
        local args=()
        local preserve_env=0
        while [[ $# -gt 0 ]]; do
            case "$1" in
                -E|--preserve-env) preserve_env=1; shift ;;
                -u|--user) args+=("-u" "$2"); shift 2 ;;
                -s|--shell) args+=("-s"); shift ;;
                --) shift; break ;;
                -*) shift ;;
                *) break ;;
            esac
        done

        if [ $preserve_env -eq 1 ]; then
            doas "${args[@]}" env "$@"
        else
            doas "${args[@]}" "$@"
        fi
    }
fi

# 2. pct alias for Proxmox VE when using doas
if command -v doas >/dev/null 2>&1 && [ -x /usr/sbin/pct ]; then
    alias pct="doas -u root /usr/sbin/pct"
fi
